#!/usr/bin/php
<?php
/**
 * @licence GPL-v2
 * Summary :
 * « You may copy, distribute and modify the software as long as
 * you track changes/dates of in source files and keep all modifications under GPL.
 * You can distribute your application using a GPL library commercially,
 * but you must also disclose the source code. »
 *
 * @link https://www.tldrlegal.com/l/gpl2
 * @see LICENSE file
 */
$required = [
    'Const.php', 'Vendor/autoload.php'
];

require_once 'dependencies.php';

loadDependencies($required);

try {
    \App\Singleton::namespaces(new \App\Library\Namespaces());
    $request = new \App\Library\Io\Request($argv, $argc);
    \App\Singleton::request($request);
    \App\Singleton::response((new \App\Library\Io\Response()));
    \App\Singleton::router((new \App\Router($request)));
    \App\Singleton::db(new \App\Library\Db(DATA_DIR . 'db.sqlite'));
    \App\Singleton::db()->exec('PRAGMA foreign_keys=ON');
    //\App\Singleton::daoType(new \App\Library\Dao\Type());
    \App\Singleton::mainFactory(new \App\Library\Factory());

} catch (\Exception $e) {
    echo "Fatal error : " . $e->getMessage() . "\n";
    exit(1);
}

try {
    $app = (new \App\Main)->run();
    \App\Singleton::response()->display($app);
} catch (\Exception $e) {
    echo "Error : " . $e->getMessage() . "\nTry typing <help>\n";
    exit(1);
}

// That's all folks !
