#!/usr/bin/php
<?php

$required = [
    'Const.php', 'Vendor/autoload.php'
];

require_once 'dependencies.php';

loadDependencies($required);

try {
    $request = new \App\Libraries\Io\Request($argv, $argc);
    \App\Singleton::request((new \App\Libraries\Io\Request($argv, $argc)));
    \App\Singleton::response((new \App\Libraries\Io\Response()));
    \App\Singleton::router((new \App\Router($request)));
    \App\Singleton::db(new \App\Libraries\Db(DATA_DIR . 'db.sqlite'));

} catch (\Exception $e) {
    \App\Helpers\Displayer::display('Fatal error : ' . $e->getMessage());
    exit(1);
}
$controller = new \App\Main();
$controller->run();

// That's all folks !
